plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.flowtrade'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    dependencies {
        api 'org.slf4j:slf4j-api:2.0.18'
        implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'
        implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.22.1")

        implementation 'io.opentelemetry:opentelemetry-api:1.64.0'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

tasks.named('test') {
	useJUnitPlatform()
}