spring.application.name=api-gateway
server.port=8000

#Services
order-service-base-url=http://localhost:8001

#Logging
logging.level.root=INFO
logging.level.com.flowtrade=INFO

# #open telemetry
# otel.service.name=${spring.application.name}
# otel.traces.exporter=console
# otel.metrics.exporter=none
# otel.logs.exporter=none