# reference: https://opentelemetry.io/docs/collector/configuration

receivers:
  otlp: # java agent sends data via otlp
    protocols: # some sdk use http and some use grpc.
    # defaults
    # gRPC → 4317
    # HTTP → 4318
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug: # pre-jaeger minimal config
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
      
      processors:
        - batch
      
      exporters: [debug , otlp/jaeger]
    
    metrics:
      receivers:
        - otlp
      
      processors:
        - batch
      
      exporters:
        - debug